name: Bedrock Action Agent

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup AWS (OIDC recommended)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::566824726150:role/agent-invoker
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Run My Bedrock Action
        uses: severity1/custom-amazon-bedrock-agent-action@v0.9.0
        with:
          agent_id: ${{ secrets.BEDROCK_AGENT_ID }}
          agent_alias_id: ${{ secrets.BEDROCK_AGENT_ALIAS }}
          action_prompt: |
           Review the Pull Request content 
           ### Summary of Changes:
            - **filename: (include line numbers)**
              - **Severity**: (Critical, High, Medium, Low)
              - **Issue Category**:
              - **Description**: (Detailed description of issue)
              - **Recommendation**:
              - **Citations**: (At least two citations from multiple sources with links)
            ### Overall Summary:
            - Reference similar prior summaries where applicable; provide a new summary if the changes are distinct.
          ignore_patterns: '**/*.md,docs/**,.github/**'
          debug: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

